import { Inter, Source_Code_Pro } from 'next/font/google'
import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import NavBar from './Components/NavBar'
import Feed from './Components/Feed'
import Footer from './Components/Footer'
import {neobrutalism} from "@clerk/themes";


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Promptify',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ClerkProvider
      appearance={{
        baseTheme: neobrutalism,
      }}
      >
        <NavBar/>
        {children}
        <Feed/>
        <Footer/>
      </ClerkProvider>
      </body>
    </html>
  )
}
