import { Source_Code_Pro } from 'next/font/google'
import '../globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import NavBar from './Components/NavBar'

const inter = Source_Code_Pro({ subsets: ['latin'] })

export const metadata = {
  title: 'Promtify',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <NavBar/>
      <ClerkProvider>
        {children}
      </ClerkProvider>
      </body>
    </html>
  )
}
